baseURL = "https://victorfran.co/"
languageCode = "en"
title = "vtfr"

[menu]
	[[menu.main]]
		name = "blog"
		pre = "<i class='fa fa-heart'></i>"
		url = "/blog/"
		weight = -110

	[[menu.contact]]
		name = "Github"
		pre = "github.svg"
		url = "https://github.com/vtfr/"
	[[menu.contact]]
		name = "LinkedIn"
		pre = "linkedin.svg"
		url = "https://www.linkedin.com/in/victorfrvl/"
	[[menu.contact]]
		name = "Twitter"
		pre = "twitter.svg"
		url = "https://twitter.com/francomermo/"